---
title: "RWorksheet#5"
author: "Andica, Benedicto, Cautivar"
date: "2024-11-06"
output: pdf_document
---
Extracting IMDB. 
1.
```{r}
library(polite)

url <- 'https://www.imdb.com/chart/toptv/?ref_=nv_tvv_250'

session <- bow(url,
               user_agent = "Educational")
session
```
```{r}
library(rvest)
library(httr)
library(dplyr)

title_list <- scrape(session) %>%
   html_nodes('h3.ipc-title__text') %>% 
  html_text
  
title_list_sub <- as.data.frame(title_list[2:26])

colnames(title_list_sub) <- "Ranks"
split_df <- strsplit(as.character(title_list_sub$Ranks),".",fixed = TRUE)
split_df <- data.frame(do.call(rbind,split_df))

colnames(split_df) <- c("Ranks","Title") 

titleAndRank <- data.frame(split_df)


ratings <- scrape(session) %>%
   html_nodes('span.ipc-rating-star--rating') %>% 
  html_text

ratingsDf <- data.frame(ratings)

numberOfPeopleVoted <- scrape(session) %>%
   html_nodes('span.ipc-rating-star--voteCount') %>% 
  html_text

cleanedVotes <- gsub('[()]', '', numberOfPeopleVoted)

cleanedVotesDf <- data.frame(cleanedVotes)

numEpisodes <- scrape(session) %>%
   html_nodes('span.sc-5bc66c50-6.OOdsw.cli-title-metadata-item:nth-of-type(2)') %>% 
  html_text

numEpisodesDf <- data.frame(numEpisodes)

Year <- scrape(session) %>%
   html_nodes('span.sc-5bc66c50-6.OOdsw.cli-title-metadata-item:nth-of-type(1)') %>% 
  html_text

YearDf <- data.frame(Year)

topShows <- cbind(titleAndRank, ratingsDf, cleanedVotesDf, numEpisodesDf, YearDf)
  
topShows 
```
1. PART II
```{r}
homePage <- 'https://www.imdb.com/chart/toptv/'
mainPage <- read_html(homePage)

links <- mainPage %>%
  html_nodes("a.ipc-title-link-wrapper") %>%
  html_attr("href")

showInfo <- lapply(links, function(link) {
  fullLink <- paste0("https://imdb.com", link)

  userRevLink <- read_html(fullLink)
  userRevPageLink <-  userRevLink  %>%
    html_nodes('a.isReview') %>%
    html_attr("href")
  
  criticRev <- userRevLink %>%
              html_nodes("span.score") %>%
              html_text()
  criticDf <- data.frame(Critic_Reviews = criticRev[2], stringsAsFactors = FALSE)
  
  popularityRating <-  userRevLink %>%
              html_nodes('[data-testid="hero-rating-bar__popularity__score"]') %>%
              html_text()
  
  userRev <- read_html(paste0("https://imdb.com",  userRevPageLink[1]))
  userRevCount <- userRev %>%
    html_nodes('[data-testid="tturv-total-reviews"]') %>%
    html_text()

  return(data.frame(User_Reviews = userRevCount, Critic = criticDf, Popularity_Rating = popularityRating)) 
})



showUrlDf <- do.call(rbind, showInfo)
showUrlDf

allShows <- cbind(topShows, showUrlDf)
allShows 
```

Extracting Amazon Product Reviews
4.
```{r}
library(rvest)
library(httr)
library(dplyr)
library(polite)
library(stringr)

urls <- c('https://www.amazon.com/s?k=backpacks&crid=35ZQ1H72MC3G9&sprefix=backpacks%2Caps%2C590&ref=nb_sb_ss_ts-doa-p_3_9', 
          'https://www.amazon.com/s?k=laptops&crid=L7MQBW7MD4SX&sprefix=laptopb%2Caps%2C1304&ref=nb_sb_noss_2',
          'https://www.amazon.com/s?k=phone+case&dc&crid=1VPDCJ87S93TL&sprefix=phone+cas%2Caps%2C451&ref=a9_asc_1',
          'https://www.amazon.com/s?k=mountain+bike&crid=1ZQR71S8XHZN6&sprefix=mountain+bik%2Caps%2C499&ref=nb_sb_noss_2',
          'https://www.amazon.com/s?k=tshirt&crid=2RQIP7MP6IYAW&sprefix=tshirt%2Caps%2C443&ref=nb_sb_noss_2')

```
```{r}
df <- list()

for (i in seq_along(urls)) {
  
    sessions <- bow(urls[i], user_agent = "Educational")
  
  productName <- scrape(sessions) %>%
    html_nodes('h2.a-size-mini') %>% 
    html_text() %>%
    head(30) 

  
  productDescription <- scrape(sessions) %>%
    html_nodes('div.productDescription') %>% 
    html_text() %>%
    head(30) 
  

  productRating <- scrape(sessions) %>%
    html_nodes('span.a-icon-alt') %>% 
    html_text() %>%
    head(30)  
  
  ratings <- as.numeric(str_extract(productRating, "\\d+\\.\\d"))
  
  
  productPrice <- scrape(sessions) %>%
    html_nodes('span.a-price') %>% 
    html_text() %>%
    head(30) 
  price <- as.numeric(str_extract(productPrice, "\\d+\\.\\d+"))
  
  
  productReview <- scrape(sessions) %>%
    html_nodes('div.review-text-content') %>% 
    html_text() %>%
    head(30)  
  
  
  dfAma <- data.frame(Product_Name = productName[1:30],
                       Description = productDescription[1:30],
                       Rating = ratings[1:30],
                       Price = price[1:30],
                       stringsAsFactors = FALSE)
  
  df[[i]] <- dfAma
}
```
```{r}
print(df[[1]])
print(df[[2]])
print(df[[3]])
print(df[[4]])
print(df[[5]])
```
```




